plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.graalvm.buildtools.native' version '1.1.14'
}

group = 'ru.oldzoomer'
version = '1.0'
description = "Yandex's Home with Alice support for StingrayTV"

java {
	toolchain {
        languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-restclient'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.jmdns:jmdns:3.6.3'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
	implementation 'org.springframework.boot:spring-boot-starter-cache-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

graalvmNative {
	metadataRepository {
    	enabled = true
    }

    binaries {
        main {
        	// Production-optimised defaults
            buildArgs.add('-H:+ReportExceptionStackTraces')
            buildArgs.add('-Os')
            buildArgs.add('-H:+StripDebugInfo')
            buildArgs.add('--no-fallback')

            // PGO bootstrap property  (set -Pbootstrap for instrumented build)
            if (project.hasProperty('bootstrap')) {
            	buildArgs.add('--pgo-instrument')
            }
            // PGO optimisation property  (set -Ppgo=/path/to/default.iprof)
            if (project.hasProperty('pgo')) {
                buildArgs.add("--pgo=${project.property('pgo')}")
            }

            // Quick build for local development  (–no-fallback, –parallelism)
           	if (project.hasProperty('quickBuild')) {
                buildArgs.add('-Ob')
                buildArgs.add('--parallelism=2')
            }

            resources.autodetect()
        }
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
